### ISSUE TITLE
Redeploying a director does not delete the associated port from the network

### ISSUE THREAD

**Issue by bsnchan** [cloudfoundry-incubator/bosh-openstack-cpi-release#114]
**Issue:** If the bosh director deployment fails, the CPI successfully deletes the failed vm but does not delete the port from the OpenStack network which causes the following error when attempting to redeploy the director:

```
Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid 'f3e26ae0-bafc-4c7e-aca2-f068a06723d2':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"OpenStack API Conflict (IP address 192.168.14.3 already allocated in subnet c1a4765c-5699-410f-a51a-ba53bbe15489). Check task debug log for details.","ok_to_retry":false}

Exit code 1
```

**Notes**

* This occurred using OpenStack CPI v35
* I lost the debug logs as this occurred in CI but I'll update the issue the next time this occurs

**Comment by voelzmo** [comment]
We might have missed a case during a failed `create_vm` which doesn't clean up ports correctly. Hard to tell which issue you ran into without having a debug log of the original failed `bosh deploy` task.

**Comment by voelzmo** [comment]
@bsnchan any updates on this issue? Did you encounter that problem again or found a way to reproduce?

**Comment by voelzmo** [comment]
Closing this for now due to inactivity. Please re-open with some debug information when the issue reoccurs.
