### ISSUE TITLE
Is this cpi supports latest openstack release Queens

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-openstack-cpi-release#118]
hi did anyone deployed on openstack Ocata to Queens latest version. Thanks in advance.

**Comment by voelzmo** [comment]
Hey @abhilash07,

OpenStack Queens is not released yet, it's [scheduled for 28th of February](https://releases.openstack.org/queens/schedule.html#q-release). We're not testing yet against Queens, so I can't say if the CPI works against Queens or not.

You can follow the discussion in #103 to learn about how our official policy for supporting future OpenStack versions is evolving.
