### ISSUE TITLE
Changing '//' to '/'  in GET os-volume_attachments API

### ISSUE THREAD

**Issue by zhongjun2** [cloudfoundry-incubator/bosh-openstack-cpi-release#126]
Hi Marco & voelzmo & Everyone,

Why we only support "//" in GET os-volume_attachments API [1].  How about we also support  "/" in GET os-volume_attachments API .
Because we only support "/" in openstack official API doc[2]

Changing 
GET /v2.1/<tenant_id>//servers/<resource_id>/os-volume_attachments
to
GET /v2.1/<tenant_id>/servers/<resource_id>/os-volume_attachments

[1] https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/docs/openstack-api-calls.md
[2] https://developer.openstack.org/api-ref/compute/#list-volume-attachments-for-an-instance

**Comment by voelzmo** [comment]
Hey @zhongjun2,

Thanks for the bug report. Is that behavior creating an error for you? If so, which OpenStack distribution and version are you running?

**Comment by zhongjun2** [comment]
Hi @voelzmo,

We got error when we attaching a volume to the instance in our own OpenStack version. That OpenStack won't pass the "//" rule.  I am so confused why we have to use "//" in this special API, and use '/' on the rest of all APIs.

**Comment by TommyLike** [comment]
Not familiar with this project, but with a quick search, I found there is a redundant splash [here](https://github.com/fog/fog-openstack/blob/dc635a68a92c62d20adedb0e8dd5f34baa385eb7/lib/fog/compute/openstack/requests/get_server_volumes.rb#L9) in the request url of project **fog-openstack**, I added a [bug report ](https://github.com/fog/fog-openstack/issues/389) there.

**Comment by zhongjun2** [comment]
Thanks TommyLike

Now, the Redundant slash already changed in fog-openstack project.
https://github.com/fog/fog-openstack/pull/390/files

**Comment by zhongjun2** [comment]
Hi @voelzmo,

Hi, since the fog-openstack code already been changed, I fix the openstack-api-calls.md doc.
Please take a look at it again, thanks.

**Comment by voelzmo** [comment]
@zhongjun2 the file you changed just contains a record of the APIs the CPI is calling. We'll have to wait for fog-openstack to release a new version which contains the above fix and then update fog-openstack in the CPI. Once that is done, the CPI should work against your OpenStack as well.

**Comment by voelzmo** [comment]
We've updated to fog-openstack 0.1.26, which includes https://github.com/fog/fog-openstack/pull/390
Next release of the CPI includes the fix.

**Comment by zhongjun2** [comment]
Thanks voelzmo!
