### ISSUE TITLE
openstack cpi does not support neutron port for fixed ip

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-incubator/bosh-openstack-cpi-release#14]
Hello,
not sure its the good place for this issue.
Anyway, i have a problem with the openstack external CPI.
My OpenStack deployments requires neutron port provisionning to set a fixed IP on the micro-bosh.

This is a blocker for bosh-init. Is this limitation only on external CPI ? 

Here the message i get

```
Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Creating VM:
        Creating vm with stemcell cid '8d3bf877-7f29-4c7e-aa20-41df10efa24d':
          CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"OpenStack API Bad Request (Fixed IP address 192.168.100.200 is already in use on instance .). Check task debug log for details.","ok_to_retry":false}
```

The message is misleading, and i could reproduce the error using the openstack nova and neutron CLI.

```
nova boot --flavor $FLAVOR_ID --key-name bosh  --image $IMAGE_ID --security-groups ab6f1484-4be2-40bd-a263-230fb2fb6d99 --nic net-id=$NETWORK_ID,v4-fixed-ip=$IP_FROM_POOL vm1
```

vm CLI creation with fixed ip was possible, provided i create a neutron port to hold the IP (following roughly the steps described in https://community.hpcloud.com/article/creating-instance-specific-fixed-ip )

```
neutron port-create --fixed-ip subnet_id=$SUBNET_ID,ip_address=$IP_FROM_POOL --name $PORT_NAME $NETWORK_ID

nova boot --flavor $FLAVOR_ID --key-name bosh  --image $IMAGE_ID --security-groups ab6f1484-4be2-40bd-a263-230fb2fb6d99 --nic net-id=$NETWORK_ID,port-id=$PORT_ID vm1
```

**Comment by cppforlife** [comment]
> Is this limitation only on external CPI ?

I dont believe so. Were you configuring your Director VM in a different way when using `bosh micro deploy`?

If you cannot use fixed IPs, you can use a floating IP for the Director VM and use dynamic networks for the rest of the deployments.

**Comment by poblin-orange** [comment]
Ok. No didnt try bosh-micro, was just wondering. Il will try to use a floating IP to workaround this issue.
Anyway, static ip should be supported in official cloustack CPI. 

Is there an open issue on this ? (floating ip are usually expensive resources, normaly dedicated to public access. cant use them for all or internal bosh deployments wiring).

**Comment by voelzmo** [comment]
@poblin-orange Which OpenStack distribution are you using? Is it actually hpcloud?

Looking at the [official OpenStack documentation](http://docs.openstack.org/admin-guide-cloud/networking_use.html#advanced-networking-operations) the command 

```
$ nova boot --image IMAGE --flavor FLAVOR --nic net-id=NET-ID, v4-fixed-ip=IP-ADDR VM_NAME
```

should work – and it does on all OpenStack distributions I tried it on. I don't know when this feature was introduced, but at least on Versions as old as Havana this is actually working.

**Comment by voelzmo** [comment]
On a second thought, it might be that you are stumbling over https://bugs.launchpad.net/nova/+bug/1408529 which was fixed in https://review.openstack.org/#/c/149905/2

[Stark and Wayne had a blog about applying this fix manually](https://blog.starkandwayne.com/2015/05/05/openstack-juno-static-ip-patch/), if you want to give it a try.

**Comment by voelzmo** [comment]
Closing this issue for now, it seems to be a problem with the openstack provider. Please re-open if there is something we can do.

**Comment by poblin-orange** [comment]
I confirm this is an issue on our provider.
Terraform user met the same issue https://github.com/hashicorp/terraform/issues/3194

We re expecting the iaas provider to fix this issue
