### ISSUE TITLE
Testcase is failing due to the old version ruby.

### ISSUE THREAD

**Issue by TommyLike** [cloudfoundry-incubator/bosh-openstack-cpi-release#146]
I have set up the test environment based on ruby 2.3.X, but the testcases are failing as below:
```
      Failure/Error: cloud.delete_stemcell('i-foo')
      NoMethodError:
        undefined method `match?' for "i-foo":String
        Did you mean?  match
```
I guess it's because of the `match?` is introduced since ruby 2.4, so we need to make the ruby version explicit in document.

**Comment by voelzmo** [comment]
Fixed with https://github.com/cloudfoundry-incubator/cf-openstack-validator/commit/bdcc74b2a4efefb2b6023c396f9a3a003dfcbaab

Thanks for reporting!
