### ISSUE TITLE
Missing instruction for s3 type blobstore

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-incubator/bosh-openstack-cpi-release#16]
Hello,
trying to use the cpi on openstack. The properties are unclear, in the spec file, i dont get the meaning of each property.
Could you give some overview of the blobstore support (local/simple ? can we use a swift provided bucket instead of amazon, sample manifest).

**Comment by voelzmo** [comment]
Hey @poblin-orange 

Only S3 compatible blobstores are supported by the bosh-agent, i.e. if you enable S3 compatibility, you can use Swift as a blobstore. Native Swift is not supported.

Please have a look at [Director blobstore configuration](http://bosh.io/docs/director-configure-blobstore.html) and [the Director `agent.blobstore` properties](http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=226#p=agent.blobstore) for additional explanation on the two options DAV vs S3 compatible blobstore and the possible properties

**Comment by voelzmo** [comment]
closing this, all blobstore clients except S3 and webdav have been remove removed in bosh: https://www.pivotaltracker.com/story/show/139905445
