### ISSUE TITLE
volume is not created on openstack kilo

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-incubator/bosh-openstack-cpi-release#19]
i followed the documentation on https://bosh.io/docs/init-openstack.html
and created/edited the template file accordingly
but the deployment fails because the volume is never created

i even tried 
```
- jobs
  persistent_disk: 20000
```
instead of the use
 persistent_disk_pool: disks

for reference https://github.com/cloudfoundry/bosh-init/issues/64

**Comment by voelzmo** [comment]
Hi @ramonskie, could you please provide some more log output and the deployment manifest you are using (with removed passwords) so we can check what actually happened?

**Comment by ramonskie** [comment]
the manifest http://pastebin.com/tZb8Rk9u
 debug logging https://www.dropbox.com/s/43gdqsjh5wceq95/logging.log?dl=0

**Comment by voelzmo** [comment]
@ramonskie From these logs it is not very evident that the volume is not created and that is the reason for the failure. The agent doesn't answer to `ping` which could have several reasons. Have you tried the steps described in http://bosh.io/docs/tips.html#unreachable-agent and could you provide the [agent logs](http://bosh.io/docs/job-logs.html#agent-logs)?

**Comment by ramonskie** [comment]
well i logged in to the created bosh vm and when i check the logs the director fails to start.
because it expects a another volume assigned to it and wants to mount it

**Comment by voelzmo** [comment]
@ramonskie could you please provide the [agent logs](http://bosh.io/docs/job-logs.html#agent-logs)?

**Comment by ramonskie** [comment]
yes i will try to have something at the end of this week

**Comment by voelzmo** [comment]
@ramonskie any updates on the logfiles?

**Comment by ramonskie** [comment]
totaly forgot about this...
i will recreate the environment today

**Comment by ramonskie** [comment]
okay i don't know what happend
but i did a clean install with the latest example manifest provided 
https://bosh.io/docs/init-openstack.html#create-manifest

and everything works as expected.

i tried to replicate the issue but i could not find one
so i think you fixed something in a later release

**Comment by voelzmo** [comment]
Thanks @ramonskie for re-testing. Please let us know if you see that behavior again. Closing this one for now.

**Comment by ramonskie** [comment]
found our issue
if the dns ip is not reachable then the agent fails.
then only issue here is that the logs are sending you in the wrong direction..

**Comment by voelzmo** [comment]
Great that you found it, thanks for the update.
