### ISSUE TITLE
Failing to create Volumes

### ISSUE THREAD

**Issue by mattsday** [cloudfoundry-incubator/bosh-openstack-cpi-release#24]
Hi there,
I am trying to deploy CF via Bosh and all goes well until it tries to create a volume.

The logs are here:
http://matt.fragilegeek.com/cf/bosh-deploy.log

My cinder api log:

> 2016-03-02 13:09:30.498 9955 DEBUG eventlet.wsgi.server [-] (9955) accepted ('10.51.8.165', 36051) server /usr/lib/python2.7/site-packages/eventlet/wsgi.py:826
> 2016-03-02 13:09:30.503 9955 INFO cinder.api.openstack.wsgi [-] POST http://10.51.8.150:8776/v1/e0e75c086b5043ecad55dafe5a6a9d26/volumes
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi [-] Exception handling resource: multi() got an unexpected keyword argument 'body'
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi Traceback (most recent call last):
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi   File "/usr/lib/python2.7/site-packages/cinder/api/openstack/wsgi.py", line 1019, in _process_stack
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi     action_result = self.dispatch(meth, request, action_args)
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi   File "/usr/lib/python2.7/site-packages/cinder/api/openstack/wsgi.py", line 1099, in dispatch
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi     return method(req=request, **action_args)
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi TypeError: multi() got an unexpected keyword argument 'body'
> 2016-03-02 13:09:30.504 9955 ERROR cinder.api.openstack.wsgi
> 2016-03-02 13:09:30.505 9955 INFO cinder.api.openstack.wsgi [-] http://10.51.8.150:8776/v1/e0e75c086b5043ecad55dafe5a6a9d26/volumes returned with HTTP 400
> 2016-03-02 13:09:30.506 9955 INFO eventlet.wsgi.server [-] 10.51.8.165 - - [02/Mar/2016 13:09:30] "POST /v1/e0e75c086b5043ecad55dafe5a6a9d26/volumes HTTP/1.1" 400 274 0.004179

I'm using an NFS backed store for Cinder. Creating volumes otherwise (via the API or Horizon) works fine, as does attaching them to instances (and booting from them)

**Comment by voelzmo** [comment]
Hi @mattsday 

when you say that you are already deploying Cloud Foundry, I assume that you installed Bosh using `bosh-init` before? That should mean that there already is a persistent disk attached to the Bosh VM, could you check that please?

I also see an interesting combination of services going on in your Keystone catalog, which distribution are you using, is that a DevStack environment? Which versions of bosh and the openstack-cpi are your using?

From what I see in the logs is that the call tries to create a disk of size `1GB` and somehow fails
```
{\"volume\":{\"display_name\":\"volume-69d93304-7a7e-41d1-9876-3b42a10a662e\",\"display_description\":\"\",\"size\":1}}
```

The CPI is making calls to the cinder v1 API, maybe that is different for the volumes you created over Horizon/the CLI. Overall it seems like you're seeing something similar to https://bugs.launchpad.net/nova/+bug/1305997 although that happened in nova. However, the fix introduced `body=nil` in the `multi()` function of the API version selector, see https://review.openstack.org/#/c/86983/3/nova/api/openstack/compute/versions.py and cinder doesn't have that parameter in its `multi` method https://github.com/openstack/cinder/blob/stable/liberty/cinder/api/versions.py#L241-L244

**Comment by mattsday** [comment]
Hi @voelzmo,
When I think about it, the bosh-init didn't create a persistent disk (but still worked) so I just created one and mapped it afterwards and then mounted it to /var/vcap/store

I found the issue - by default RDO packstack sets this for liberty in /etc/cinder/cinder.conf:

> enable_v1_api = false

Changing it to true worked a charm. Thanks!

**Comment by friegger** [comment]
@mattsday: We double checked on this issue, but could not reproduce the exact problem (we don't have PackStack, though). In your logs Cinder v1 is advertised in the service catalog, but the API was not responsive due to the *enable_v1_api = false*. That is strange, a disabled API should not show up in the service catalog. The CPI shows a helpful error message, if Cinder v1 is not advertised in the service catalog and that should be sufficient.
