### ISSUE TITLE
I should be able to boot from a volume rather than local storage

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-incubator/bosh-openstack-cpi-release#30]
We had a user on slack that was attempting to deploy a VM with a flavor set to 0GB root and ephemeral disks. They referenced [this bug](https://bugs.launchpad.net/mos/+bug/1424624/comments/3) as the rational.

Looking at the code, there appears to be a `boot_from_volume` property that looks promising. However, the size of this volume is still determined by the disk size defined in the flavor. It seems like making the boot volume size independently configurable and listing the `boot_from_volume` property on the main CPI doc on bosh.io should solve the user's use case.

**Comment by cppforlife** [comment]
cc @voelzmo

**Comment by voelzmo** [comment]
Thanks for the highlighting, @cppforlife :) I was a few days out of office, sorry for the delay.

I guess it makes sense to have the root disk size adjustable. I'll adjust the linked story in our backlog and put in something similar to AWS's [`ephemeral disk`](http://bosh.io/docs/aws-cpi.html#resource-pools) in the `resource_pool`. Does that sound reasonable?

**Comment by voelzmo** [comment]
Marking as open-for-contributions as we've got different priorities for now. For anyone who likes to take shot at this: I've added more detailed tasks and background info [in the corresponding tracker story](https://www.pivotaltracker.com/story/show/116653013)

**Comment by voelzmo** [comment]
Implemented in release v25.
