### ISSUE TITLE
Add support image v2 and volume v2 api

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry-incubator/bosh-openstack-cpi-release#31]
Currently the openstack cpi supports only image (glance) v1 and volume (cinder) v1 api.
https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/docs/openstack-api-calls.md

But some public IaaS provides only v2 apis.

Do you plan to support the v2 api?

**Comment by voelzmo** [comment]
Hey @kei-yamazaki, thanks for the notice. We are aware that the CPI currently uses APIs marked as deprecated, such as Cinder v1. Note, however, that glance v1 is still in the [`supported` stage](http://developer.openstack.org/api-ref-image-v1.html).

We will move to cinder v2 in the near future, glance v2 is not planned yet.

Out of curiosity: Which public provider doesn't support glance v1 and cinder v1?

**Comment by kei-yamazaki** [comment]
@voelzmo, thanks for reply.

For example, "ConoHa" provides only glance v2 and cinder v2 (sorry Japanese docs). 
https://www.conoha.jp/docs/

**Comment by voelzmo** [comment]
@kei-yamazaki we have a story in the backlog for an update to [Glance V2](https://www.pivotaltracker.com/story/show/118677313) and [Cinder V2](https://www.pivotaltracker.com/story/show/118677339). However, they're currently marked as `open-for-contribution`, as we won't get to them very quickly, I think.

**Comment by cppforlife** [comment]
We will contribute it: https://www.pivotaltracker.com/story/show/126520625

**Comment by kei-yamazaki** [comment]
@voelzmo @cppforlife, thanks for information.

We are considering a contribution in my team.
I'll contact you if there is any progress.

**Comment by voelzmo** [comment]
Support for cinder v2 and glance v2 is in CPI releae v26

**Comment by cppforlife** [comment]
@kei-yamazaki let us know if you hit some problem. we had to apply a few fixes to fog-openstack to properly support v2.

**Comment by kei-yamazaki** [comment]
@cppforlife, Awesome fixes! Thanks!
Our team is going to use the new OpenStack CPI soon.
I'll let you know if we find some problem.
