### ISSUE TITLE
Different AZ for volume and instance

### ISSUE THREAD

**Issue by Infra-Red** [cloudfoundry-incubator/bosh-openstack-cpi-release#34]
Hi!
At current moment I have the need to move one of my Bosh deployed instances with persistent disk to another availability zone, but CPI [does now allow](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/availability_zone_provider.rb#L39) to attach volume from one availability zone to instance in another. 
Is it somehow possible to attach existing volume to instance without loosing any data?
Thanks!

**Comment by cppforlife** [comment]
@Infra-Red i'm pretty sure that's an openstack limitation and not the cpi. you could try:

- snapshot your disk and making another volume in a different AZ from that snapshot
- remove persistent disk from your instances in the manifest
- deploy them to a different AZ without disks
- `bosh stop name/id`
- use `bosh attach disk <volume id in the new az> name/id`
- update your manifest to state that you have persistent disks
- `bosh start name/id`
- `bosh deploy` to make it make there are no pending changes

potential future enhancement might be to introduce new CPI method (and Director functionality) to clone disks between locations for such migrations.

**Comment by Infra-Red** [comment]
@cppforlife it is possible to mount volume to instance in different zones manually. I will try `bosh attach` feature and share result.
Thanks!

**Comment by voelzmo** [comment]
@Infra-Red The CPI allows for different AZs in VMs and Disks by specifying [`openstack.ignore_server_availability_zone`](http://bosh.io/jobs/openstack_cpi?source=github.com/cloudfoundry-incubator/bosh-openstack-cpi-release&version=24#p=openstack.ignore_server_availability_zone). Not sure if that helps you with that case, though.

**Comment by cppforlife** [comment]
@Infra-Red is your volumes backend not separated into azs just like compute?

**Comment by voelzmo** [comment]
@Infra-Red Could you solve your issue or workaround it somehow?
