### ISSUE TITLE
openstack bosh-init fails on mbus agent

### ISSUE THREAD

**Issue by frantisek121** [cloudfoundry-incubator/bosh-openstack-cpi-release#38]
Hi,

I am trying to use bosh.yml template (https://bosh.io/docs/init-openstack.html), but I got stuck on log message:

[httpClient] 2016/05/20 08:29:11 DEBUG - Sending POST request with body {"method":"ping","arguments":[],"reply_to":"989ff387-e93e-41bb-7d9d-74bcef5e7e96"}, endpoint https://mbus:mbus-password@<my FIP>:6868/agent

bosh-init deploy ./bosh.yml output finishes with:

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Waiting until instance is ready:
        Sending ping to the agent:
          Performing request to agent endpoint 'https://mbus:mbus-password@<my FIP>:6868/agent':
            Performing POST request:
              Post https://mbus:mbus-password@<my FIP>:6868/agent: dial tcp <my FIP>:6868: getsockopt: connection refused

I was checking vm that was created and I see that port 6868 is not open. Should it be open? Is there a sudo for vcap user for further investigation? 

Any idea what the issue may be? I have checked sec group and network connections, no FW, all seems to be fine.

Thank you

Br

Frantisek Dolezel

**Comment by voelzmo** [comment]
That sounds like an issue during agent bootstrap. Possible reasons are many, just trying to eliminate a few:
* Can you boot a VM in OpenStack using `nova boot` and ssh into it?
* If that works, try again to `bosh-init` and can you access the VM's console in Horizon during that?
  * Please check the bosh-agent log at `/var/vcap/bosh/log/current` and paste it here

Hope that helps finding the issue.

**Comment by frantisek121** [comment]
Hi,

my problem was that I used a custom flavor. I used the default now and all
is good.

BTW: How would I check the log? I was able to login only with vcap user
that has no sudo rights. No need to answer that as it is no blocker for me,
I am just curious...

Thank you for support !!!

Br

Frantisek Dolezel

**Comment by voelzmo** [comment]
@frantisek121 Checking the log works after `sudo su -`. The default password for vcap is `c1oudc0w`, as stated in the [documentation](https://bosh.io/docs/vm-config.html#global)
