### ISSUE TITLE
Unable to connect to the OpenStack Image Service API

### ISSUE THREAD

**Issue by fanux** [cloudfoundry-incubator/bosh-openstack-cpi-release#42]
I got an image error, but could not  fixed it.

```bash
Command 'deploy' failed:
  creating stemcell (bosh-openstack-kvm-ubuntu-trusty-go_agent 3232.4):
    CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Unable to connect to the OpenStack Image Service API: Expected([200, 204]) \u003c=\u003e Actual(404 Not Found)\nexcon.error.response\n  :body          =\u003e \"{\\\"error\\\": {\\\"message\\\": \\\"The resource could not be found.\\\", \\\"code\\\": 404, \\\"title\\\": \\\"Not Found\\\"}}\"\n  :cookies       =\u003e [\n  ]\n  :headers       =\u003e {\n    \"Content-Length\" =\u003e \"93\"\n    \"Content-Type\"   =\u003e \"application/json\"\n    \"Date\"           =\u003e \"Thu, 23 Jun 2016 07:04:42 GMT\"\n    \"Server\"         =\u003e \"Apache/2.4.7 (Ubuntu)\"\n    \"Vary\"           =\u003e \"X-Auth-Token\"\n  }\n  :host          =\u003e \"192.168.1.121\"\n  :local_address =\u003e \"192.168.1.121\"\n  :local_port    =\u003e 35495\n  :path          =\u003e \"/identity//tokens\"\n  :port          =\u003e 80\n  :reason_phrase =\u003e \"Not Found\"\n  :remote_ip     =\u003e \"192.168.1.121\"\n  :status        =\u003e 404\n  :status_line   =\u003e \"HTTP/1.1 404 Not Found\\r\\n\"\n. Check task debug log for details.","ok_to_retry":false}
```

image service API is  http://192.168.1.121:9292
```bash
{"versions": [{"status": "CURRENT", "id": "v2.3", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.2", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.1", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.0", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.1", "links": [{"href": "http://192.168.1.121:9292/v1/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.0", "links": [{"href": "http://192.168.1.121:9292/v1/", "rel": "self"}]}]}
```
How can I solve my problem.

**Comment by fanux** [comment]
I solved this problem.  

I use the identity v3 lead to this error.
just change the auth_url

http://domain/identity => http://domain/identity/v2.0/

**Comment by beyhan** [comment]
@fanux it has to be the complete `identity` URL. It can be found in the OpenStack UI. We support both v2 and v3.

**Comment by fanux** [comment]
@beyhan ,  but as I know, the manifest of v2 and v3 are difference.

**Comment by chrisrana** [comment]
I am facing same issue,but I am using v2 only.
 CPI 'create_stemcell' method responded with error: `CmdError{"type":"Bosh::Clouds::CloudError","message":"Unable to connect to the OpenStack Image Service API: Expected([200, 204]) \u003c=\u003e Actual(404 Not Found)\nexcon.error.response\n  :body          =\u003e \"{\\\"error\\\": {\\\"message\\\": \\\"The resource could not be found.\\\", \\\"code\\\": 404, \\\"title\\\": \\\"Not Found\\\"}}\"\n  :cookies       =\u003e [\n  ]\n  :headers       =\u003e {\n    \"Content-Length\" =\u003e \"93\"\n    \"Content-Type\"   =\u003e \"application/json; charset=ISO-8859-1\"\n    \"Date\"           =\u003e \"Mon, 19 Sep 2016 14:54:33 GMT, Mon, 19 Sep 2016 14:54:33 GMT\"\n    \"Server\"         =\u003e \"Jetty(9.2.z-SNAPSHOT)\"\n    \"Vary\"           =\u003e \"X-Auth-Token\"\n    \"Via\"            =\u003e \"1.1 Repose (Repose/7.1.4.0)\"\n    \"x-trans-id\"     =\u003e \"1672f85e-ffb0-41dd-9c3c-434266fcde21\"\n  }\n  :host          =\u003e \"us-virginia-1.cloud.cisco.com\"\n  :local_address =\u003e \"10.20.0.211\"\n  :local_port    =\u003e 36992\n  :path          =\u003e \"/v2.0/v3/auth/tokens\"\n  :port          =\u003e 5000\n  :reason_phrase =\u003e \"Not Found\"\n  :remote_ip     =\u003e \"128.107.39.5\"\n  :status        =\u003e 404\n  :status_line   =\u003e \"HTTP/1.1 404 Not Found\\r\\n\"\n. Check task debug log for details.","ok_to_retry":false}
`
