### ISSUE TITLE
bosh deploy fails while compiling packages

### ISSUE THREAD

**Issue by MoizArif** [cloudfoundry-incubator/bosh-openstack-cpi-release#45]
Hi,

I am trying to run bosh deploy and the deployment errors out with the following errors:

![image](https://cloud.githubusercontent.com/assets/3896078/16840569/cd6de6b8-49ee-11e6-8b1d-3efcf43f252e.png)

what seems to be the issue here?

Thanks 
Moiz

**Comment by voelzmo** [comment]
@MoizArif The VMs didn't come up successfully in OpenStack, but went straight to state `error`. There might be additional debug information [contained in the debug log](http://bosh.io/docs/job-logs.html#director-logs) (accessible via `bosh task 20 --debug`, as stated in your output above), or in the OpenStack nova logs.

**Comment by MoizArif** [comment]
@voelzmo, Yes is suspected that too. but couldn't narrow down the exact reason for the VMs going into error state. Attached is the task 20 --debug log, can you please help me find the root cause for this. 

[task20.txt](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/files/363980/task20.txt)

**Comment by voelzmo** [comment]
@MoizArif It seems to be that your haven't enough capacity on your compute nodes available. OpenStack reports
```
"fault\": {\"message\": \"No valid host was found. There are not enough hosts available!
```

**Comment by MoizArif** [comment]
I just checked my nova scheduler logs and apparently it verifies what we see in bosh logs 
`nova.filters Filter ComputeFilter returned 0 hosts `

ahh. let me figure out the resources and get back to you. Thanks.

**Comment by MoizArif** [comment]
@voelzmo : I solved the resource issues and now the VMs get created while running bosh deploy. Facing with another issue. can you take a look at the logs.

![image](https://cloud.githubusercontent.com/assets/3896078/16870327/796803a8-4a9a-11e6-9869-02a3cef3ca5b.png)
[task48-log.txt](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/files/365668/task48-log.txt)

**Comment by MoizArif** [comment]
bosh docs state the following reasons for this:

1. blocked network connectivity between the Agent on a new VM and NATS (typically the Director VM)
2. bootstrapping problem on the VM and/or wrong configuration of the Agent
3. blocked or slow boot times of the VM

3rd is not applicable in my case. let me look at #1 & #2 meanwhile if you can find specific issue from the logs.

**Comment by MoizArif** [comment]
My bosh director VM is not pingable from the worker VMs or from other normal VMs on the same network using the same security group. The director can ping the router interface. However, 2 normal VMs on the same network with same SG can ping each other directly. also 2 VMs can on different networks can ping each other using same SG.

**Comment by voelzmo** [comment]
@MoizArif That sounds like an OpenStack related configuration problem where I can hardly help, sorry about that.

**Comment by MoizArif** [comment]
@voelzmo Yes, it was openstack related. i solved that but still back to the old problem
` Timed out pinging to 2daf77da-7b3f-4f3c-87e0-4d985d15f7ce after 600 seconds (00:10:25)`

Same screenshot as attached in the above comment. 
From the Logs:

> D, [2016-07-19T07:44:49.347483 #26013] DEBUG -- : excon.error {:error=>#<Excon::Errors::NotFound: Expected([200, 203]) <=> Actual(404 Not Found)
> excon.error.response
>   :body          => "{\"itemNotFound\": {\"message\": \"Metadata item was not found\", \"code\": 404}}"
>   :cookies       => [
>   ]
>   :headers       => {
>     "Connection"           => "close"
>     "Content-Length"       => "73"
>     "Content-Type"         => "application/json; charset=UTF-8"
>     "Date"                 => "Tue, 19 Jul 2016 07:44:49 GMT"
>     "X-Compute-Request-Id" => "req-1fcfcdd5-6772-477c-bfaa-a04f05d4475a"
>   }
>   :host          => "x.x.x.x"
>   :local_address => "1.1.1.200"
>   :local_port    => 40507
>   :path          => "/v2/5ce8c65d17fd453d9641e19b5b6a6eff/servers/d11ef74e-4e4d-421b-a2d7-5845afb13ca3/metadata/registry_key"
>   :port          => 8774
>   :reason_phrase => "Not Found"
>   :remote_ip     => "x.x.x.x"
>   :status        => 404
>   :status_line   => "HTTP/1.1 404 Not Found\r\n"
> >}
> D, [2016-07-19T07:44:49.347633 #26013] DEBUG -- : VM with id 'd11ef74e-4e4d-421b-a2d7-5845afb13ca3' has no 'registry_key' tag
> , exit_status: pid 26013 exit 0

**Comment by voelzmo** [comment]
That HTTP 404 is expected and okay. It is related to a cpi feature which you aren't using right now. If the BOSH Director cannot ping the VM it creates, you will see the above error of `Timed out pinging to...`, and this seems to be related to your network setup.

**Comment by MoizArif** [comment]
Hi @voelzmo 
I was able to clean up my environment and solve the connectivity related issues. 
Now the VMs got created and could contact other VMs too and the director. 
However, my deploy event failed with the following error message:

```
E, [2016-07-22 10:30:13 #25291] [canary_update(consul_z1/0 (d4db0398-7052-460c-8289-36b2d0cff98c))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::AgentJobNotRunning: 'consul_z1/0 (d4db0398-7052-460c-8289-36b2d0cff98c)' is not running after update. Review logs for failed jobs: consul_agent>
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:109:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:11:in `with_instance_update_and_event_creation'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:111:in `update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:113:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:111:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:110:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:105:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2016-07-22 10:30:13 #25291] [] ERROR -- DirectorJobRunner: Worker thread raised exception: 'consul_z1/0 (d4db0398-7052-460c-8289-36b2d0cff98c)' is not running after update. Review logs for failed jobs: consul_agent - /var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:109:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater/instance_state.rb:11:in `with_instance_update_and_event_creation'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/instance_updater.rb:111:in `update'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:113:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:111:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/event_log.rb:99:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:110:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh-director-1.3262.3.0/lib/bosh/director/job_updater.rb:105:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/bosh_common-1.3262.3.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.3.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-07-22 10:30:13 #25291] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2016-07-22 10:30:13 #25291] [task:6] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2016-07-22 10:30:13 #25291] [task:6] DEBUG -- DirectorJobRunner: (0.000384s) SELECT NULL
D, [2016-07-22 10:30:13 #25291] [task:6] DEBUG -- DirectorJobRunner: (0.001263s) SELECT "stemcells".* FROM "stemcells" INNER JOIN "deployments_stemcells" ON ("deployments_stemcells"."stemcell_id" = "stemcells"."id") WHERE ("deployments_stemcells"."deployment_id" = 1)
```

Any idea about what does this point to?
Thanks.

**Comment by MoizArif** [comment]
The consul_agent logs on the consul VM shows the following error:
```

==> Starting Consul agent...
==> Error starting agent: Failed to start Consul server: Failed to parse any CA certificates

```

However, i have added the required certificates and keys in the cf-stub.yml file.

**Comment by rushins** [comment]
Hello 

I have very much similar errors. anyone have idea. i am getting timeout .

Started creating missing vms > ha_proxy_z1/0 (91109bc8-18eb-4ba3-8370-10d2eb17fbf1)
  Started creating missing vms > clock_global/0 (348ca045-5d5c-43c0-a65a-ccb39472f333)
  Started creating missing vms > api_worker_z1/0 (db15272c-0d95-446a-8563-6a31aee059f3)
   Failed creating missing vms > clock_global/0 (348ca045-5d5c-43c0-a65a-ccb39472f333): Timed out pinging to bc7dddbc-e3e2-4238-b5b2-dd69347196a6 after 600 seconds (00:11:32)
   Failed creating missing vms > api_worker_z1/0 (db15272c-0d95-446a-8563-6a31aee059f3): Timed out pinging to 1a9f4279-cdb5-4be1-9a3e-e6df9acdfaba after 600 seconds (00:11:49)
   Failed creating missing vms > ha_proxy_z1/0 (91109bc8-18eb-4ba3-8370-10d2eb17fbf1): Timed out pinging to 476868c6-a288-4420-833c-35f69395573d after 600 seconds (00:11:54)

Error 450002: Timed out pinging to bc7dddbc-e3e2-4238-b5b2-dd69347196a6 after 600 seconds

BR
Rushi.

**Comment by voelzmo** [comment]
@rushins You can find some information how to debug the situation in the [official documentation at bosh.io](http://bosh.io/docs/tips.html#unreachable-agent)

**Comment by jreg2k** [comment]
HI @MoizArif , how did you cleaned up your environment and solve the connectivity related issues  ?

Regards.

**Comment by MoizArif** [comment]
Hi @jreg2k, i had some mis-configurations in my setup. I had some stingy firewall rules that were blocking most of the traffic. Getting the right firewall rules in place, allowed traffic in and out from the OpenStack SG and reconfigure OpenStack networking solved those issues.

**Comment by jreg2k** [comment]
HI @MoizArif thanks for your answer. It was a network issue for me too.
Regards.
