### ISSUE TITLE
Can't configure additional security groups on per-instance-group basis

### ISSUE THREAD

**Issue by craigbookwalter** [cloudfoundry-incubator/bosh-openstack-cpi-release#53]
In order to help us secure our bosh deployments, we would like to be able to specify a default security group in the cloud-config, which all VMs would receive upon deployment, and then specify in the deployment manifest additional security groups needed for certain jobs. For example, if we deploy a load balancer and a jump host with the same director, it would be good to be able to put them into different security groups. 

@ljfranklin guided me to giving this a try:

```
vm_extensions:
  - name: lb-sec-groups
    cloud_properties:
      security_groups: [public-http, ssh]
```

but deployment failed with this error:

```
Started updating instance lb > lb/xyz (0) (canary). Failed: CPI error 'Bosh::Clouds::CloudError' with message 'Cannot define security groups in both network and resource pool.' in 'create_vm' CPI method (00:00:14)

Error 100: CPI error 'Bosh::Clouds::CloudError' with message 'Cannot define security groups in both network and resource pool.' in 'create_vm' CPI method
```
It would be cool if the groups could be merged instead of throwing the error.

**Comment by cppforlife** [comment]
@ljfranklin does aws cpi also contain this behaviour? i think this was done on purpose to avoid accidently adding wrong security groups (ie only one place specifies them)

**Comment by ljfranklin** [comment]
@cppforlife looks like it, although the AWS CPI seems to silently ignore security groups from the network rather than throwing an error if both are specifed:  https://github.com/cloudfoundry-incubator/bosh-aws-cpi-release/blob/4f97a64d169be634888abe80e64daaa04a8f1899/src/bosh_aws_cpi/lib/cloud/aws/instance_param_mapper.rb#L121. Not great...

**Comment by voelzmo** [comment]
OpenStack CPI works as expected. As @cppforlife stated: This was a conscious decision to error out.
