### ISSUE TITLE
Missing information about why failure occurred during OpenStack VM deployment

### ISSUE THREAD

**Issue by mcpeak** [cloudfoundry-incubator/bosh-openstack-cpi-release#57]
While attempting to deploy bosh to OpenStack, I kept receiving failures with no indication of why.  It turned out that the floating IP that I was attempting to use was no longer available.  The only error I received from the command line was:

OpenStack API service not found error: Expected([200, 203]) \u003c=\u003e Actual(404 Not Found)

While attempting to access the Compute API for a specific instance which was unable to be created.  Therefore it was trying to access: `/v2/{my_tenant}/servers/.json`.  Obviously the instance id was blank, but the error handling failed to recognize that.

This could be enhanced by passing back better errors/warnings about which step failed.

**Comment by mcpeak** [comment]
Looks like the help file suggests that this means "your VM creation has failed in some way".  A small enhancement to the doc with a checklist of things to validate may be useful.

- create XLarge VM from bosh image
- attach named security group
- attach to private network IP
- attach to public network IP
- retrieve named key

This may be overkill though...

etc

**Comment by voelzmo** [comment]
@mcpeak Could you please provide the actual output and debug log of your deployment task? If we're going to change the output, I'd like to have an idea what the current situation looks like. Thanks!

**Comment by mcpeak** [comment]
Sorry, I don't have access to the log anymore.  I agree the full log is pretty necessary to do something meaningful with this.  I'm happy to close it.

**Comment by voelzmo** [comment]
Please re-open if the issue comes back.
