### ISSUE TITLE
Bosh-Openstack-CPI can be deployed on openstack Newton Release ??

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/bosh-openstack-cpi-release#58]
Hi everyone is any one tested bosh-cpi on Openstack-Newton release. If any one deployed please let me know expected error. Thanks in advance.

Regards

Abhilash S

**Comment by voelzmo** [comment]
Hi @abhilash07,

we currently don't test the OpenStack CPI with the Newton release. When OpenStack ditributors release their products for the Newton release, we will include it in our official test pipelines. This will most likely take a few more weeks, so stay tuned.
