### ISSUE TITLE
bosh deploy Bosh::Clouds::CloudError' with message 'OpenStack API service not found error: Expected([201]) Actual(404 Not Found)

### ISSUE THREAD

**Issue by harshalk91** [cloudfoundry-incubator/bosh-openstack-cpi-release#59]
Failed compiling packages > ruby-2.3/ca5b2d16eac54f907ab6c1f454d9c81560f311a2: CPI error 'Bosh::Clouds::CloudError' with message 'OpenStack API service not found error: Expected([201]) <=> Actual(404 Not Found)
excon.error.response
:body => "{"NeutronError": {"message": "The resource could not be found.", "type": "HTTPNotFound", "detail": ""}}"
:cookies => [
]
:headers => {
"Content-Length" => "103"
"Content-Type" => "application/json; charset=UTF-8"
"Date" => "Fri, 13 Jan 2017 19:47:31 GMT"
"X-Openstack-Request-Id" => "req-74cee047-9a6b-4db9-a7ec-96fe16861618"
}
:host => "xxx.xxx.com"
:local_address => "192.168.1.14"
:local_port => 42626
:path => "/v2.0/ports"
:port => 9696
:reason_phrase => "Not Found"
:remote_ip => "10.104.68.18"
:status => 404
:status_line => "HTTP/1.1 404 Not Found\r\n"

After this issue i logged in into the **Bosh Director VM** and tested following command: 

**curl https://my-openstack-host:9696 --insecure**
{"versions": [{"status": "CURRENT", "id": "v2.0", "links": [{"href": "http://my-openstack-host:9696/v2.0**

**curl https://my-openstack-host:5000/v2.0 --insecure**
{"version": {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}], "id": "v2.0", "links": [{"href": "https://my-openstack-host:5000/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}]}}

**curl https://my-openstack-host:9292 --insecure**
{"versions": [{"status": "CURRENT", "id": "v2.3", "links": [{"href": "http://my-openstack-host:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.2", "links": [{"href": "http://my-openstack-host:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.1", "links": [{"href": "http://my-openstack-host:/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.0", "links": [{"href": "http://my-openstack-host:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.1", "links": [{"href": "http://my-openstack-host:9292/v1/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.0", "links": [{"href": "http://my-openstack-host:9292/v1/", "rel": "self"}]}]}

**Comment by voelzmo** [comment]
@harshalk91 The error indicates that your OpenStack installation doesn't provide neutron. Is this a DevStack by any chance?

The OpenStack CPI uses neutron by default to manage networks. See [the documentation on bosh.io](http://bosh.io/docs/openstack-nova-networking.html) on how to enable nova-networking compatibility.

**Comment by harshalk91** [comment]
@voelzmo We use openstack mitaka. I edited cf yml and able to go forward with that. But now there is another strange error while performing bosh deploy.  [](https://github.com/cloudfoundry/bosh/issues/1563) ---
director_uuid: e23b5aa1-d934-4176-a9c4-680c74c4b1f0
Here is my cf deployment yml:
meta:
  environment: dev

  floating_static_ips:
  - 10.104.160.87
networks:
  - name: floating
    type: vip
    cloud_properties:
      net_id: dc8385e3-3771-481d-ba98-4abf1f21c30b
      security_groups: []
  - name: cf2
    type: manual
    subnets:
    - range: 192.168.1.0/24
      gateway: 192.168.1.1
      dns:
      - 10.19.1.23
      reserved:
      - 192.168.1.1 - 192.168.1.60
      static:
      - 192.168.1.61 - 192.168.1.254

      cloud_properties:
        net_id: ee216d00-1adb-4b00-a3f8-5d0a5514c142
        security_groups: ["cf"]

  - name: cf1
    type: manual
    subnets:
    - range: 10.104.160.0/20
      gateway: 10.104.160.1
      dns:
      - 10.19.1.23
      static:
      - 10.104.160.212
      - 10.104.160.240
      - 10.104.160.77
      - 10.104.160.81 - 10.104.160.97

      cloud_properties:
        net_id: dc8385e3-3771-481d-ba98-4abf1f21c30b
        security_groups: ["cf"]

**Comment by voelzmo** [comment]
Okay, closing this one to continue the conversation in one place
