### ISSUE TITLE
Error while creating a vm with an attached floating ip.

### ISSUE THREAD

**Issue by shoudusse** [cloudfoundry-incubator/bosh-openstack-cpi-release#62]
Hello,
I'm running the cf-openstack-validator and i'm getting an error at the "can attach floating IP to a VM" stage:

    E, [2017-02-02T14:07:51.872517 #66763] ERROR -- : OpenStack API service not found error: Expected([200]) <=> Actual(404 Not Found)
    excon.error.response
      :body          => "{\"message\":\"Api does not exist\",\"request_id\":\"E307D556-D4BE-481D-83D2-4B6372BD4D1D\"}"
      :cookies       => [
      ]
      :headers       => {
        "Connection"      => "keep-alive"
        "Content-Type"    => "application/json; charset=ISO-8859-1"
        "Date"            => "Thu, 08 Feb 2017 14:02:47 GMT"
        "Server"          => "Web Server"
        "x-sdk-ErrorType" => "ApigatewayException"
      }
      :host          => "my-neutron-endpoint"
      :local_address => "192.168.1.11"
      :local_port    => 51944
      :path          => "/v2.0/ports/"
      :port          => 443
      :reason_phrase => "Not Found"
      :remote_ip     => "10.72.33.11"
      :status        => 404
      :status_line   => "HTTP/1.1 404 Not Found\r\n"

After some debugging, I found that the CPI retrieves some informations about the floating ip provide in the manifest : [here](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/floating_ip.rb#L9)
In my case, the result is:

    {"id"=>"2fc3bb90-b6ca-4d2b-83e8-07cbe729e40a",
    "status"=>"DOWN",
    "router_id"=>"",
    "tenant_id"=>"7220c537e5994943903ce9f8de2f0f57",
    "floating_network_id"=>"0a2228f2-7f8a-45f1-8e09-9039e1d09975",
    "fixed_ip_address"=>"",
    "floating_ip_address"=>"10.72.130.97",
    "port_id"=>""}

The port_id is an empty string but the key exists.
So the CPI try to retrieve the port configuration [here](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/floating_ip.rb#L12) but since the port_id is an empty string, this results to this faulty API call "/v2.0/ports/"

Don't really know if the good choice is to improve [the port_id existence test](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/master/src/bosh_openstack_cpi/lib/cloud/openstack/floating_ip.rb#L11) or something else.

Thanks for your help.

**Comment by voelzmo** [comment]
That's quite interesting, I've never seen all empty strings being returned on a query like this, where it should be all `nil` instead.
Out of curiosity: Which OpenStack installation and version is this?

Seems like we should check for `.empty?` additionally to existence of the property `port_id`.

**Comment by shoudusse** [comment]
I ran some tests on 2 different OpenStack distributions and effectively the results are not the same:
# Vanilla OpenStack
    GET /v2.0/floatingips/<floating_id>
    { ... , "port_id": null, ... }

# Huawei FusionSphere OpenStack
    GET /v2.0/floatingips/<floating_id>
    { ... , "port_id": "", ... }

I will submit a Pull Request with the fix you proposed in the previous comment

Thanks for your help

**Comment by Kiemes** [comment]
Fix has been merged. Closing.
