### ISSUE TITLE
Persistent disk with volume id <volume_id> could not be found

### ISSUE THREAD

**Issue by zhoutiekui** [cloudfoundry-incubator/bosh-openstack-cpi-release#66]
Hi, I had encountered an mounting disk error as follow. I had confirmed from the OpenStack console that the Disk had been created  and attached to the VM  And I don't know the root cause , is there some suggestion about how to analyze the problem. I am confused by this question. Thank you very much.

My stemcell is :
bosh-stemcell-3312.12-openstack-kvm-ubuntu-trusty-go_agent.tgz

Error logs:
Started validating
  Validating release 'bosh'... Finished (00:00:04)
  Validating release 'bosh-openstack-cpi'... Finished (00:00:00)
  Validating release 'uaa'... Finished (00:00:03)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Validating stemcell... Finished (00:00:02)
Finished validating (00:00:11)

Started installing CPI
  Compiling package 'ruby_openstack_cpi/9485b5753d4609e92e1491ff991cb28fbde81445'... Finished (00:00:00)
  Compiling package 'bosh_openstack_cpi/dd0bab98dbb820af3ec59b364badfed02ffe3f3b'... Finished (00:00:00)
  Installing packages... Finished (00:00:01)
  Rendering job templates... Finished (00:00:01)
  Installing job 'openstack_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:02)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-openstack-kvm-ubuntu-trusty-go_agent/3312.12'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Waiting for the agent on VM '0fb01aee-5bd0-4140-b3a4-10cfcf3a5b57'... Finished (00:00:00)
  Stopping jobs on instance 'unknown/0'... Finished (00:00:00)
  Deleting VM '0fb01aee-5bd0-4140-b3a4-10cfcf3a5b57'... Finished (00:00:30)
  Creating VM for instance 'bosh/0' from stemcell 'da038593-bba5-4d77-bdeb-b575d0a28897'... Finished (00:02:02)
  Waiting for the agent on VM 'efaa1689-8efb-4a24-801b-f166f02ca7e2' to be ready... Finished (00:02:54)
  Creating disk... Finished (00:00:12)
  Attaching disk '2b361d0f-1b90-4738-9756-c626d1106d3c' to VM 'efaa1689-8efb-4a24-801b-f166f02ca7e2'... Failed (00:00:42)
Failed deploying (00:06:24)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Updating instance disks:
        Updating disks:
          Deploying disk:
            Mounting disk:
              Sending 'get_task' to the agent:
                Agent responded with error: Action Failed get_task: Task 8fefe0f0-be87-44ca-63e3-5ac47916c2ec result: Persistent disk with volume id '2b361d0f-1b90-4738-9756-c626d1106d3c' could not be found

**Comment by cppforlife** [comment]
please try using latest version of bosh-init or cli v2.

**Comment by beyhan** [comment]
The latest stemcell [3363.9](https://s3.amazonaws.com/bosh-core-stemcells/openstack/bosh-stemcell-3363.9-openstack-kvm-ubuntu-trusty-go_agent.tgz) could also help. It makes the bosh-agent's communication with the  OpenStack metadata service more resilient. See [pull-request] (https://github.com/cloudfoundry/bosh-agent/pull/117)

If you want to analyze the issue it should be possible to ssh into the VM. There you can find the bosh-agent logs under the folder `/var/vcap/bosh/logs/`. The most recent one is called `current`. From the logs should be possible to find out why agent could finish the task.

**Comment by zhoutiekui** [comment]
@beyhan @cppforlife  thanks for your reply,  actually I also found that the vcap password is not c1oudc0w, I cannot even login to see the content of the bosh logs with the vcap user privilleges. What caused the password not take effect ?  and is there any way to generate a new password ? 
Thanks.

**Comment by beyhan** [comment]
@zhoutiekui new stemcells have disabled the default password for the `vcap` user. Now you have to specify a password. See here how to specify it: https://www.cloudfoundry.org/hardening-the-vcap-users-password-on-bosh-vms/

**Comment by voelzmo** [comment]
Seems like the initial error has been fixed. Please open new issues when a new problem comes up.
