### ISSUE TITLE
The v3 auth method cannot get the specied project/tenant name.

### ISSUE THREAD

**Issue by zhoutiekui** [cloudfoundry-incubator/bosh-openstack-cpi-release#68]
When I specify the project name but didn't take effect as there are serveral projects in my environment. And the bosh openstack cpi choose the first one selected by the /v3/users/#{user_id}/projects API rather than the configuration.so with the wrong project and auth failed. 

 I need to change the code to my project and It can take affect.

/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/fog-1.35.0/lib/fog/openstack/core.rb
old: options[:openstack_project_name] = projects_body['projects'].first['name']
new:  options[:openstack_project_name] = "myProject"

**Comment by voelzmo** [comment]
@zhoutiekui could you please show us your CPI configuration in the manifest? Please make sure to remove passwords and/or endpoints before pasting it in here. Thanks!

**Comment by zhoutiekui** [comment]
I use bosh v27
    openstack:
      auth_url: https://mydomain/v3
      tenant: eu-de
      project: eu-de
      domain: username
      username: username
      api_key: password
      default_key_name: microbosh
      default_security_groups:
      - default

**Comment by voelzmo** [comment]
* can you please put your code in within three ```, so that whitespace formatting works correctly? Are all the indentations correct?
* In keystone v3, you don't need to set `tenant`, only `project` is relevant
* Did I understand correctly, that you're changing the value for `project`, but it has no effect and you still get a different project?

**Comment by zhoutiekui** [comment]
@voelzmo : I change the file "/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/fog-1.35.0/lib/fog/openstack/core.rb"， change the column "options[:openstack_project_name] = projects_body['projects'].first['name']" to "options[:openstack_project_name] = "myproject" ", and it works. It authenticate with the right project I specified.

**Comment by voelzmo** [comment]
@zhoutiekui I don't know what it is that you're doing. It seems you are running tempest tests which use fog? This is about the bosh-openstack-cpi, so I don't think I can help you with this.

**Comment by zhoutiekui** [comment]
@voelzmo  
I am testing the pivotal cloud foundry on openstack.

**Comment by voelzmo** [comment]
The path you are talking about `/home/tempest-web/tempest/web/vendor/bundle/ruby/2.2.0/gems/fog-1.35.0/lib/fog/openstack/core.rb` is a tempest test. We don't do tempest testing. If there is a problem with a PCF test, please contact PCF support.
