### ISSUE TITLE
creating stemcell timedout

### ISSUE THREAD

**Issue by manojRy** [cloudfoundry-incubator/bosh-openstack-cpi-release#95]
Hello,
I have been trying to create a bosh directory on openstack. I am having a manifest file and I tried to deploy it and ended up with an error while creating the stemcell.
<img width="945" alt="stem" src="https://user-images.githubusercontent.com/16360625/31999491-b16e6f58-b993-11e7-9e75-42773f0367f2.PNG">

P:S: I can see the stemcell or partially created stem cell under private images in the cloud.
Thanks

**Comment by voelzmo** [comment]
Hey @manojRy 

what is the state your image ends up in? Does it just take long to become 'active' or does it enter any 'error' state? Also: can you manually upload the same image using e.g. Horizon or the OpenStack CLI?

Out of curiosity: what kind of OpenStack installation are you running this against? Is this a DevStack or some local installation?

**Comment by manojRy** [comment]
Hi @voelzmo . I have resolved it by adding `state_timeout: 3600` in the bosh.yml file. This is because my cloud provider is taking more time than usual cloud providers. With the above line, I have extended it to an hour which by default is no more than 5 mins. I haven't tried it uploading manually, I am trying it on a devstack
